name: Python CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f coding/python/black-hole-simulator-2d/requirements.txt ]; then pip install -r coding/python/black-hole-simulator-2d/requirements.txt; fi

      - name: Compile sources
        run: |
          python -m compileall -q coding/python/black-hole-simulator-2d/src

